# **🩺Clinical Trial💊**

**Overview:**

Get ready to step into the shoes of a Data Scientist at a top pharmaceutical company! In this Project, you’ll clean, explore, and analyze a clinical trial dataset to determine if Auralin, a new oral insulin, can replace Novodra, the current injectable standard. From tackling messy data to conducting rigorous statistical tests, you'll uncover insights that could shape the future of diabetes treatment!

**DATA SUMMARY**

This is a dataset about 500 patients of which 350 patients participated in a clinical trial. None of the patients were using Novodra (a popular injectable insulin) or Auralin (the oral insulin being researched) as their primary source of insulin before. All were experiencing elevated HbA1c levels.

All 350 patients were treated with Novodra to establish a baseline HbA1c level and insulin dose. After 4 weeks, which isn’t enough time to capture all the change in HbA1c that can be attributed by the switch to Auralin or Novodra:

*   175 patients switched to Auralin for 24 weeks
*  175 patients continued using Novodra for 24 weeks

Data about patients feeling some adverse effects is also recorded.

**Additional information:**


*   Insulin resistance varies person to person, which is why both starting median daily dose and ending median daily dose are required, i.e., to calculate change in dose.

*   It is important to test drugs and medical products in the people they are meant to help. People of different age, race, sex, and ethnic group must be included in clinical trials. This diversity is reflected in the patients table.

### Reading The CSV Files And Copy The Data Frame In To Another Data Frame

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
#reading adverse_reaction csv file
df=pd.read_csv("/content/adverse_reactions.csv")

In [ ]:
# copy the file of adverse_reaction
reactions=df.copy()

In [ ]:
#reading patients  csv file
df1=pd.read_csv("/content/patients.csv")

In [ ]:
df1

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
0,1,female,Zoe,Wellish,576 Brown Bear Drive,Rancho California,California,92390.0,United States,951-719-9170ZoeWellish@superrito.com,7/10/1976,121.7,66,19.6
1,2,female,Pamela,Hill,2370 University Hill Road,Armstrong,Illinois,61812.0,United States,PamelaSHill@cuvox.de+1 (217) 569-3204,4/3/1967,118.8,66,19.2
2,3,male,Jae,Debord,1493 Poling Farm Road,York,Nebraska,68467.0,United States,402-363-6804JaeMDebord@gustr.com,2/19/1980,177.8,71,24.8
3,4,male,Liêm,Phan,2335 Webster Street,Woodbridge,NJ,7095.0,United States,PhanBaLiem@jourrapide.com+1 (732) 636-8246,7/26/1951,220.9,70,31.7
4,5,male,Tim,Neudorf,1428 Turkey Pen Lane,Dothan,AL,36303.0,United States,334-515-7487TimNeudorf@cuvox.de,2/18/1928,192.3,27,26.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
498,499,male,Mustafa,Lindström,2530 Victoria Court,Milton Mills,ME,3852.0,United States,207-477-0579MustafaLindstrom@jourrapide.com,4/10/1959,181.1,72,24.6
499,500,male,Ruman,Bisliev,494 Clarksburg Park Road,Sedona,AZ,86341.0,United States,928-284-4492RumanBisliev@gustr.com,3/26/1948,239.6,70,34.4
500,501,female,Jinke,de Keizer,649 Nutter Street,Overland Park,MO,64110.0,United States,816-223-6007JinkedeKeizer@teleworm.us,1/13/1971,171.2,67,26.8
501,502,female,Chidalu,Onyekaozulu,3652 Boone Crockett Lane,Seattle,WA,98109.0,United States,ChidaluOnyekaozulu@jourrapide.com1 360 443 2060,2/13/1952,176.9,67,27.7
502,503,male,Pat,Gersten,2778 North Avenue,Burr,Nebraska,68324.0,United States,PatrickGersten@rhyta.com402-848-4923,5/3/1954,138.2,71,19.3

In [ ]:
# copy the file of patients
patients=df1.copy()

In [ ]:
patients

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
0,1,female,Zoe,Wellish,576 Brown Bear Drive,Rancho California,California,92390.0,United States,951-719-9170ZoeWellish@superrito.com,7/10/1976,121.7,66,19.6
1,2,female,Pamela,Hill,2370 University Hill Road,Armstrong,Illinois,61812.0,United States,PamelaSHill@cuvox.de+1 (217) 569-3204,4/3/1967,118.8,66,19.2
2,3,male,Jae,Debord,1493 Poling Farm Road,York,Nebraska,68467.0,United States,402-363-6804JaeMDebord@gustr.com,2/19/1980,177.8,71,24.8
3,4,male,Liêm,Phan,2335 Webster Street,Woodbridge,NJ,7095.0,United States,PhanBaLiem@jourrapide.com+1 (732) 636-8246,7/26/1951,220.9,70,31.7
4,5,male,Tim,Neudorf,1428 Turkey Pen Lane,Dothan,AL,36303.0,United States,334-515-7487TimNeudorf@cuvox.de,2/18/1928,192.3,27,26.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
498,499,male,Mustafa,Lindström,2530 Victoria Court,Milton Mills,ME,3852.0,United States,207-477-0579MustafaLindstrom@jourrapide.com,4/10/1959,181.1,72,24.6
499,500,male,Ruman,Bisliev,494 Clarksburg Park Road,Sedona,AZ,86341.0,United States,928-284-4492RumanBisliev@gustr.com,3/26/1948,239.6,70,34.4
500,501,female,Jinke,de Keizer,649 Nutter Street,Overland Park,MO,64110.0,United States,816-223-6007JinkedeKeizer@teleworm.us,1/13/1971,171.2,67,26.8
501,502,female,Chidalu,Onyekaozulu,3652 Boone Crockett Lane,Seattle,WA,98109.0,United States,ChidaluOnyekaozulu@jourrapide.com1 360 443 2060,2/13/1952,176.9,67,27.7
502,503,male,Pat,Gersten,2778 North Avenue,Burr,Nebraska,68324.0,United States,PatrickGersten@rhyta.com402-848-4923,5/3/1954,138.2,71,19.3

In [ ]:
#reading treatments  csv file
df3=pd.read_csv("/content/treatments.csv")

In [ ]:
# copy the file of treatments
treatments=df3.copy()

In [ ]:
#reading treatments_cut  csv file
df4=pd.read_csv('/content/treatments_cut.csv')

In [ ]:
# copy the file of treatments_cut
treatments_cut=df4.copy()

**Table -> adverse_reactions**



* **given_name:** the given name of each patient in the Master Patient Index that took part in the clinical trial and had an adverse reaction (includes both patients treated Auralin and Novodra)

*  **surname:** the surname of each patient in the Master Patient Index that took part in the clinical trial and had an adverse reaction (includes both patients treated Auralin and Novodra)
*  **adverse_reaction:** the adverse reaction reported by the patient

**Table -> patients:**

* **patient_id:** the unique identifier for each patient in the Master Patient Index (i.e. patient database) of the pharmaceutical company that is producing Auralin
* **assigned_sex:** the assigned sex of each patient at birth (male or female)
* **given_name:** the given name (i.e. first name) of each patient
* **surname:** the surname (i.e. last name) of each patient
* **address:** the main address for each patient
* **city:** the corresponding city for the main address of each patient
* **state:** the corresponding state for the main address of each patient
* **zip_code:** the corresponding zip code for the main address of each patient
* **country:** the corresponding country for the main address of each patient (all United states for this clinical trial)
* **contact:** phone number and email information for each patient
* **birthdate:** the date of birth of each patient (month/day/year). The inclusion criteria for this clinical trial is age >= 18 (there is no maximum age because diabetes is a growing problem among the elderly population)
* **weight:** the weight of each patient in pounds (lbs)
* **hight:** the height of each patient in inches (in)
* **bmi:** the Body Mass Index (BMI) of each patient. BMI is a simple calculation using a person's height and weight. The formula is BMI = kg/m2 where kg is a person's weight in kilograms and m2 is their height in metres squared. A BMI of 25.0 or more is overweight, while the healthy range is 18.5 to 24.9. The inclusion criteria for this clinical trial is 16 >= BMI >= 38.


**Table -> treatments** :

 *  **given_name:** the given name of each patient in the Master Patient Index that took part in the clinical trial
 *  **surname:** the surname of each patient in the Master Patient Index that took part in the clinical trial
 *  **aurlin:**the baseline median daily dose of insulin from the week prior to switching to Auralin (the number before the dash) and the ending median daily dose of insulin at the end of the 24 weeks of treatment measured over the 24th week of treatment (the number after the dash). Both are measured in units (shortform 'u'), which is the international unit of measurement and the standard measurement for insulin.
 * **novodra:**same as above, except for patients that continued treatment with Novodra
 *  **hba1c_start:** the patient's HbA1c level at the beginning of the first week of treatment. HbA1c stands for Hemoglobin A1c. The HbA1c test measures what the average blood sugar has been over the past three months. It is thus a powerful way to get an overall sense of how well diabetes has been controlled. Everyone with diabetes should have this test 2 to 4 times per year. Measured in %.
 * **hba1c_end:** the patient's HbA1c level at the end of the last week of treatment
hba1c_change: the change in the patient's HbA1c level from the start of treatment to the end, i.e., hba1c_start -  hba1c_end. For Auralin to be deemed effective, it must be "noninferior" to Novodra, the current standard for insulin. This "noninferiority" is statistically defined as the upper bound of the 95% confidence interval being less than 0.4% for the difference between the mean HbA1c changes for Novodra and Auralin (i.e. Novodra minus Auralin).

**Table -> treatment_cut:**

 *  **given_name:** the given name of each patient in the Master Patient Index that took part in the clinical trial
 *  **surname:** the surname of each patient in the Master Patient Index that took part in the clinical trial
 *  **aurlin:**the baseline median daily dose of insulin from the week prior to switching to Auralin (the number before the dash) and the ending median daily dose of insulin at the end of the 24 weeks of treatment measured over the 24th week of treatment (the number after the dash). Both are measured in units (shortform 'u'), which is the international unit of measurement and the standard measurement for insulin.
 * **novodra:**same as above, except for patients that continued treatment with Novodra
 *  **hba1c_start:** the patient's HbA1c level at the beginning of the first week of treatment. HbA1c stands for Hemoglobin A1c. The HbA1c test measures what the average blood sugar has been over the past three months. It is thus a powerful way to get an overall sense of how well diabetes has been controlled. Everyone with diabetes should have this test 2 to 4 times per year. Measured in %.
 * **hba1c_end:** the patient's HbA1c level at the end of the last week of treatment
hba1c_change: the change in the patient's HbA1c level from the start of treatment to the end, i.e., hba1c_start -  hba1c_end. For Auralin to be deemed effective, it must be "noninferior" to Novodra, the current standard for insulin. This "noninferiority" is statistically defined as the upper bound of the 95% confidence interval being less than 0.4% for the difference between the mean HbA1c changes for Novodra and Auralin (i.e. Novodra minus Auralin).

####**Cleaning The Given Data of 🩺Clinical Trial💊.**

#### **Cleaning The Columns Of Adverse_Reaction**

In [ ]:
#Cleaning the columns of adverse_ reaction
reactions.head()

  given_name     surname           adverse_reaction
0      berta  napolitani  injection site discomfort
1       lena        baer               hypoglycemia
2     joseph         day               hypoglycemia
3     flavia  fiorentino                      cough
4    manouck     wubbels          throat irritation

In [ ]:
#Cleaning the columns of adverse_ reaction
reactions.rename(columns={'given_name':'first_name','surname':'last_name'},inplace='True')

In [ ]:
#Cleaning the columns data of adverse_ reaction

reactions['first_name']=reactions.first_name.str.title()

reactions['last_name']=reactions.last_name.str.title()

reactions['adverse_reaction']=reactions.adverse_reaction.str.title()

#Removing special chr in name
import re
def remove_special_chars(name):
    return re.sub('[^A-Za-z ]+', '', name)


reactions['first_name'] = reactions['first_name'].apply(remove_special_chars)

reactions['last_name'] = reactions['last_name'].apply(remove_special_chars)

In [ ]:
reactions.head()

  first_name   last_name           adverse_reaction
0      Berta  Napolitani  Injection Site Discomfort
1       Lena        Baer               Hypoglycemia
2     Joseph         Day               Hypoglycemia
3     Flavia  Fiorentino                      Cough
4    Manouck     Wubbels          Throat Irritation

**Insights from the Cleaning the columns data of adverse_ reaction**

*   We changed the font style of columns to make them more readable.
*   We renamed columns for better data clarity.
*   There is no null values

###Cleaning the columns of patients

In [ ]:
patients.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 503 entries, 0 to 502
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   patient_id    503 non-null    int64
 1   assigned_sex  503 non-null    object
 2   given_name    503 non-null    object
 3   surname       503 non-null    object
 4   address       491 non-null    object
 5   city          491 non-null    object
 6   state         491 non-null    object
 7   zip_code      491 non-null    float64
 8   country       491 non-null    object
 9   contact       491 non-null    object
 10  birthdate     503 non-null    object
 11  weight        503 non-null    float64
 12  height        503 non-null    int64
 13  bmi           503 non-null    float64
dtypes: float64(3), int64(2), object(9)
memory usage: 55.1+ KB

In [ ]:
#cleaning the column of patients
#just change the name of the columns

patients.rename(columns={'given_name':'first_name','surname':'last_name'},inplace='True')

In [ ]:
#checking  the null values in this columns
patients.first_name.isnull().sum()
#there is no null values in this columns

#Removing Special char in name
patients['first_name'] = patients['first_name'].apply(remove_special_chars)

In [ ]:
#checking  the null values in this columns
patients.last_name.isnull().sum()
#there is no null values in this columns

#Removing Special char in name
patients['last_name'] = patients['last_name'].apply(remove_special_chars)


**Insights from the Cleaning the columns data of patientstable**

**first_name and last_name columns**
* We changed the font style of columns to make them more readable.
* There is no null values

In [ ]:
#Cleaning the gender columns data of patients

#just change the name of the columns

patients.rename(columns={'assigned_sex' : 'gender'},inplace='True')



#changing  the font style of gender
patients['gender']=patients['gender'].str.title()

patients['gender'].head()

0    Female
1    Female
2      Male
3      Male
4      Male
Name: gender, dtype: object

In [ ]:
#checking  the null values in this columns
patients.gender.isnull().sum()
#there is no null values in this columns

0

**Insights from the Cleaning the columns data of patientstable**

**gender column**:


*   We changed the font style of columns to make them more readable.
*  There is no null values

In [ ]:
patients

,patient_id,gender,first_name,last_name,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
0,1,Female,Zoe,Wellish,576 Brown Bear Drive,Rancho California,California,92390.0,United States,951-719-9170ZoeWellish@superrito.com,7/10/1976,121.7,66,19.6
1,2,Female,Pamela,Hill,2370 University Hill Road,Armstrong,Illinois,61812.0,United States,PamelaSHill@cuvox.de+1 (217) 569-3204,4/3/1967,118.8,66,19.2
2,3,Male,Jae,Debord,1493 Poling Farm Road,York,Nebraska,68467.0,United States,402-363-6804JaeMDebord@gustr.com,2/19/1980,177.8,71,24.8
3,4,Male,Lim,Phan,2335 Webster Street,Woodbridge,NJ,7095.0,United States,PhanBaLiem@jourrapide.com+1 (732) 636-8246,7/26/1951,220.9,70,31.7
4,5,Male,Tim,Neudorf,1428 Turkey Pen Lane,Dothan,AL,36303.0,United States,334-515-7487TimNeudorf@cuvox.de,2/18/1928,192.3,27,26.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
498,499,Male,Mustafa,Lindstrm,2530 Victoria Court,Milton Mills,ME,3852.0,United States,207-477-0579MustafaLindstrom@jourrapide.com,4/10/1959,181.1,72,24.6
499,500,Male,Ruman,Bisliev,494 Clarksburg Park Road,Sedona,AZ,86341.0,United States,928-284-4492RumanBisliev@gustr.com,3/26/1948,239.6,70,34.4
500,501,Female,Jinke,de Keizer,649 Nutter Street,Overland Park,MO,64110.0,United States,816-223-6007JinkedeKeizer@teleworm.us,1/13/1971,171.2,67,26.8
501,502,Female,Chidalu,Onyekaozulu,3652 Boone Crockett Lane,Seattle,WA,98109.0,United States,ChidaluOnyekaozulu@jourrapide.com1 360 443 2060,2/13/1952,176.9,67,27.7
502,503,Male,Pat,Gersten,2778 North Avenue,Burr,Nebraska,68324.0,United States,PatrickGersten@rhyta.com402-848-4923,5/3/1954,138.2,71,19.3

In [ ]:
#Cleaning the address columns data of patients

#cheeking for null values
patients.address.isnull().sum()

12

In [ ]:
patients['address'].str.split(" ")

0           [576, Brown, Bear, Drive]
1      [2370, University, Hill, Road]
2          [1493, Poling, Farm, Road]
3             [2335, Webster, Street]
4           [1428, Turkey, Pen, Lane]
                    ...
498           [2530, Victoria, Court]
499     [494, Clarksburg, Park, Road]
500             [649, Nutter, Street]
501     [3652, Boone, Crockett, Lane]
502             [2778, North, Avenue]
Name: address, Length: 503, dtype: object

In [ ]:
# spliting address and create new column for street_no and street_name
patients['street_no'] = patients['address'].astype(str).apply(lambda x: x.split(" ")[0] if isinstance(x, str) else None)
patients['street_no']

0       576
1      2370
2      1493
3      2335
4      1428
       ...
498    2530
499     494
500     649
501    3652
502    2778
Name: street_no, Length: 503, dtype: object

In [ ]:
# spliting address and create new column for street_no and street_name
patients['street_name'] = patients['address'].astype(str).apply(lambda x: " ".join(x.split(" ")[1:]).replace(","," ") if isinstance(x, str) else None)

In [ ]:
patients['street_name']

0          Brown Bear Drive
1      University Hill Road
2          Poling Farm Road
3            Webster Street
4           Turkey Pen Lane
               ...
498          Victoria Court
499    Clarksburg Park Road
500           Nutter Street
501     Boone Crockett Lane
502            North Avenue
Name: street_name, Length: 503, dtype: object

In [ ]:
#droping addres and we replace with the street_name and steet_no
patients=patients.drop(['address'],axis=1)

In [ ]:
patients.head()

,patient_id,gender,first_name,last_name,city,state,zip_code,country,contact,birthdate,weight,height,bmi,street_no,street_name
0,1,Female,Zoe,Wellish,Rancho California,California,92390.0,United States,951-719-9170ZoeWellish@superrito.com,7/10/1976,121.7,66,19.6,576,Brown Bear Drive
1,2,Female,Pamela,Hill,Armstrong,Illinois,61812.0,United States,PamelaSHill@cuvox.de+1 (217) 569-3204,4/3/1967,118.8,66,19.2,2370,University Hill Road
2,3,Male,Jae,Debord,York,Nebraska,68467.0,United States,402-363-6804JaeMDebord@gustr.com,2/19/1980,177.8,71,24.8,1493,Poling Farm Road
3,4,Male,Lim,Phan,Woodbridge,NJ,7095.0,United States,PhanBaLiem@jourrapide.com+1 (732) 636-8246,7/26/1951,220.9,70,31.7,2335,Webster Street
4,5,Male,Tim,Neudorf,Dothan,AL,36303.0,United States,334-515-7487TimNeudorf@cuvox.de,2/18/1928,192.3,27,26.1,1428,Turkey Pen Lane

**Insights from the Cleaning the columns data of patientstable**

 **address column**:

* The column was split into two new columns: Street_no and Street_name for more redable.
* there is null values

* droping addres and we replace with the street_name and steet_no

In [ ]:
patients['contact'].explode().str.split(" ")

0                 [951-719-9170ZoeWellish@superrito.com]
1              [PamelaSHill@cuvox.de+1, (217), 569-3204]
2                     [402-363-6804JaeMDebord@gustr.com]
3         [PhanBaLiem@jourrapide.com+1, (732), 636-8246]
4                      [334-515-7487TimNeudorf@cuvox.de]
                             ...
498        [207-477-0579MustafaLindstrom@jourrapide.com]
499                 [928-284-4492RumanBisliev@gustr.com]
500              [816-223-6007JinkedeKeizer@teleworm.us]
501    [ChidaluOnyekaozulu@jourrapide.com1, 360, 443,...
502               [PatrickGersten@rhyta.com402-848-4923]
Name: contact, Length: 503, dtype: object

In [ ]:
# spliting contact and create new column for Phone and Email
patients['phone_num']=patients['contact'].str.extract(r'([+]?[0-9]+[\s+]?[\(]?[\-]?[0-9]+[\)]?[\s+]?[0-9]+[\s+]?[\-]?[0-9]{,4})')
patients['phone_num']

0           951-719-9170
1      +1 (217) 569-3204
2           402-363-6804
3      +1 (732) 636-8246
4           334-515-7487
             ...
498         207-477-0579
499         928-284-4492
500         816-223-6007
501       1 360 443 2060
502         402-848-4923
Name: phone_num, Length: 503, dtype: object

In [ ]:
# spliting contact and create new column for Phone and Email
patients['email_id']=patients['contact'].str.extract(r'([a-zA-Z][a-zA-Z0-9.-]+@[a-zA-Z0-9.-]+[.]+[a-zA-z]{,5})')
patients['email_id']

0               ZoeWellish@superrito.com
1                   PamelaSHill@cuvox.de
2                   JaeMDebord@gustr.com
3              PhanBaLiem@jourrapide.com
4                    TimNeudorf@cuvox.de
                     ...
498      MustafaLindstrom@jourrapide.com
499               RumanBisliev@gustr.com
500            JinkedeKeizer@teleworm.us
501    ChidaluOnyekaozulu@jourrapide.com
502             PatrickGersten@rhyta.com
Name: email_id, Length: 503, dtype: object

In [ ]:
#Cleaning the city columns data of patients

#cheeking for null values
patients['city'].isna().sum()

12

In [ ]:
#droping addres and we replace with the phone_num and email_id
patients=patients.drop(['contact'],axis=1)

In [ ]:
patients.head()

,patient_id,gender,first_name,last_name,city,state,zip_code,country,birthdate,weight,height,bmi,street_no,street_name,phone_num,email_id
0,1,Female,Zoe,Wellish,Rancho California,California,92390.0,United States,7/10/1976,121.7,66,19.6,576,Brown Bear Drive,951-719-9170,ZoeWellish@superrito.com
1,2,Female,Pamela,Hill,Armstrong,Illinois,61812.0,United States,4/3/1967,118.8,66,19.2,2370,University Hill Road,+1 (217) 569-3204,PamelaSHill@cuvox.de
2,3,Male,Jae,Debord,York,Nebraska,68467.0,United States,2/19/1980,177.8,71,24.8,1493,Poling Farm Road,402-363-6804,JaeMDebord@gustr.com
3,4,Male,Lim,Phan,Woodbridge,NJ,7095.0,United States,7/26/1951,220.9,70,31.7,2335,Webster Street,+1 (732) 636-8246,PhanBaLiem@jourrapide.com
4,5,Male,Tim,Neudorf,Dothan,AL,36303.0,United States,2/18/1928,192.3,27,26.1,1428,Turkey Pen Lane,334-515-7487,TimNeudorf@cuvox.de

**Insights from the Cleaning the columns data of patientstable**

**Contact column**:

*  The column was split into two new columns: Phone and email for more redable.
*  there is null values
*  droping addres and we replace with the phone_num and email_id

**Insights from the Cleaning the columns data of patientstable**

**city**:


*   No cleaning was performed becuse there is null values

In [ ]:
#Cleaning the state columns data of patients

#cheeking for null values
patients['state'].isna().sum()

12

In [ ]:
# Define a dictionary mapping full state names to abbreviations
state_abbrev = {
    'California': 'CA',
    'New York': 'NY',
    'Illinois': 'IL',
    'Florida': 'FL',
    'Nebraska': 'NE'
}

# Convert state names to abbreviations
patients['state'] = patients['state'].replace(state_abbrev)

**Insights from the Cleaning the columns data of patientstable**

**state**:

* Convert full state names to their respective  
  abbreviations
*  there is null values

In [ ]:
#Cleaning the state columns data of patients

#cheeking for null values
patients['country'].isna().sum()

12

**Insights from the Cleaning the columns data of patientstable**

**country**:

No cleaning was performed becuse there is null values

In [ ]:
#Cleaning the zip_code columns data of patients

#there is null values in this columan and also datatype
patients['zip_code'].isna().sum()

12

**Insights from the Cleaning the columns data of patientstable**

**zip_code**:
No cleaning was performed, but it was noted that there were null values and that the data type was not correct.

In [ ]:
#Cleaning the birthdate columns data of patients

#finding the null values
patients['birthdate'].isna().sum()

#There is no null values inthis columan

#converting the birthdate columns to date column data of patients
patients['birthdate']=pd.to_datetime(patients['birthdate'],format="%m/%d/%Y")

In [ ]:
patients['birthdate'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 503 entries, 0 to 502
Series name: birthdate
Non-Null Count  Dtype
--------------  -----
503 non-null    datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 4.1 KB

**Insights from the Cleaning the columns data of patientstable**

**birthdate**:
 The data type was converted to datetime. No null values were found.

In [ ]:
patients.rename(columns={'weight':'height','height':'weight'},inplace='True')

**Insights from the Cleaning the columns data of patientstabe**l

* We inter change the weight and height columns names because the columns names are inncorrect


**weight**: No cleaning was performed.

**height**: No cleaning was performed.

**bmi**: No cleaning was performed.

The values in the weight, height, and bmi columns are already correct, so no cleaning is needed.

In [ ]:
patients

,patient_id,gender,first_name,last_name,city,state,zip_code,country,birthdate,height,weight,bmi,street_no,street_name,phone_num,email_id
0,1,Female,Zoe,Wellish,Rancho California,CA,92390.0,United States,1976-07-10,121.7,66,19.6,576,Brown Bear Drive,951-719-9170,ZoeWellish@superrito.com
1,2,Female,Pamela,Hill,Armstrong,IL,61812.0,United States,1967-04-03,118.8,66,19.2,2370,University Hill Road,+1 (217) 569-3204,PamelaSHill@cuvox.de
2,3,Male,Jae,Debord,York,NE,68467.0,United States,1980-02-19,177.8,71,24.8,1493,Poling Farm Road,402-363-6804,JaeMDebord@gustr.com
3,4,Male,Lim,Phan,Woodbridge,NJ,7095.0,United States,1951-07-26,220.9,70,31.7,2335,Webster Street,+1 (732) 636-8246,PhanBaLiem@jourrapide.com
4,5,Male,Tim,Neudorf,Dothan,AL,36303.0,United States,1928-02-18,192.3,27,26.1,1428,Turkey Pen Lane,334-515-7487,TimNeudorf@cuvox.de
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
498,499,Male,Mustafa,Lindstrm,Milton Mills,ME,3852.0,United States,1959-04-10,181.1,72,24.6,2530,Victoria Court,207-477-0579,MustafaLindstrom@jourrapide.com
499,500,Male,Ruman,Bisliev,Sedona,AZ,86341.0,United States,1948-03-26,239.6,70,34.4,494,Clarksburg Park Road,928-284-4492,RumanBisliev@gustr.com
500,501,Female,Jinke,de Keizer,Overland Park,MO,64110.0,United States,1971-01-13,171.2,67,26.8,649,Nutter Street,816-223-6007,JinkedeKeizer@teleworm.us
501,502,Female,Chidalu,Onyekaozulu,Seattle,WA,98109.0,United States,1952-02-13,176.9,67,27.7,3652,Boone Crockett Lane,1 360 443 2060,ChidaluOnyekaozulu@jourrapide.com
502,503,Male,Pat,Gersten,Burr,NE,68324.0,United States,1954-05-03,138.2,71,19.3,2778,North Avenue,402-848-4923,PatrickGersten@rhyta.com

In [ ]:
patients.state

0      CA
1      IL
2      NE
3      NJ
4      AL
       ..
498    ME
499    AZ
500    MO
501    WA
502    NE
Name: state, Length: 503, dtype: object

###**Treatment Column**

In [ ]:
treatments.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 280 entries, 0 to 279
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   given_name    280 non-null    object
 1   surname       280 non-null    object
 2   auralin       280 non-null    object
 3   novodra       280 non-null    object
 4   hba1c_start   280 non-null    float64
 5   hba1c_end     280 non-null    float64
 6   hba1c_change  171 non-null    float64
dtypes: float64(3), object(4)
memory usage: 15.4+ KB

In [ ]:
treatments

,given_name,surname,auralin,novodra,hba1c_start,hba1c_end,hba1c_change
0,veronika,jindrová,41u - 48u,-,7.63,7.20,NaN
1,elliot,richardson,-,40u - 45u,7.56,7.09,0.97
2,yukitaka,takenaka,-,39u - 36u,7.68,7.25,NaN
3,skye,gormanston,33u - 36u,-,7.97,7.62,0.35
4,alissa,montez,-,33u - 29u,7.78,7.46,0.32
...,...,...,...,...,...,...,...
275,albina,zetticci,45u - 51u,-,7.93,7.73,0.20
276,john,teichelmann,-,49u - 49u,7.90,7.58,NaN
277,mathea,lillebø,23u - 36u,-,9.04,8.67,0.37
278,vallie,prince,31u - 38u,-,7.64,7.28,0.36
279,samúel,guðbrandsson,53u - 56u,-,8.00,7.64,0.36

In [ ]:
treatments_cut

,given_name,surname,auralin,novodra,hba1c_start,hba1c_end,hba1c_change
0,jožka,resanovič,22u - 30u,-,7.56,7.22,0.34
1,inunnguaq,heilmann,57u - 67u,-,7.85,7.45,NaN
2,alwin,svensson,36u - 39u,-,7.78,7.34,NaN
3,thể,lương,-,61u - 64u,7.64,7.22,0.92
4,amanda,ribeiro,36u - 44u,-,7.85,7.47,0.38
...,...,...,...,...,...,...,...
65,rovzan,kishiev,32u - 37u,-,7.75,7.41,0.34
66,jakob,jakobsen,-,28u - 26u,7.96,7.51,0.95
67,bernd,schneider,48u - 56u,-,7.74,7.44,0.30
68,berta,napolitani,-,42u - 44u,7.68,7.21,NaN
69,armina,sauvé,36u - 46u,-,7.86,7.40,NaN

In [ ]:
treatments_cut.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70 entries, 0 to 69
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   given_name    70 non-null     object
 1   surname       70 non-null     object
 2   auralin       70 non-null     object
 3   novodra       70 non-null     object
 4   hba1c_start   70 non-null     float64
 5   hba1c_end     70 non-null     float64
 6   hba1c_change  42 non-null     float64
dtypes: float64(3), object(4)
memory usage: 4.0+ KB

**Concatenating the treatments and treatments_cut dataframes**

In [ ]:
treatments_data= pd.concat([treatments ,treatments_cut])

In [ ]:
treatments_data

,given_name,surname,auralin,novodra,hba1c_start,hba1c_end,hba1c_change
0,veronika,jindrová,41u - 48u,-,7.63,7.20,NaN
1,elliot,richardson,-,40u - 45u,7.56,7.09,0.97
2,yukitaka,takenaka,-,39u - 36u,7.68,7.25,NaN
3,skye,gormanston,33u - 36u,-,7.97,7.62,0.35
4,alissa,montez,-,33u - 29u,7.78,7.46,0.32
...,...,...,...,...,...,...,...
65,rovzan,kishiev,32u - 37u,-,7.75,7.41,0.34
66,jakob,jakobsen,-,28u - 26u,7.96,7.51,0.95
67,bernd,schneider,48u - 56u,-,7.74,7.44,0.30
68,berta,napolitani,-,42u - 44u,7.68,7.21,NaN
69,armina,sauvé,36u - 46u,-,7.86,7.40,NaN

**Created a new column hba1c_change which is the difference between hba1c_start and hba1c_end.**

In [ ]:
treatments_data['hba1c_change']=treatments_data['hba1c_start'] - treatments_data['hba1c_end']

**Renamed the columns given_name and surname to first_name and last_nam**

In [ ]:
treatments_data.rename(columns={'given_name':'first_name','surname':'last_name'},inplace='True')

In [ ]:
treatments_data.head()

,first_name,last_name,auralin,novodra,hba1c_start,hba1c_end,hba1c_change
0,veronika,jindrová,41u - 48u,-,7.63,7.20,0.43
1,elliot,richardson,-,40u - 45u,7.56,7.09,0.47
2,yukitaka,takenaka,-,39u - 36u,7.68,7.25,0.43
3,skye,gormanston,33u - 36u,-,7.97,7.62,0.35
4,alissa,montez,-,33u - 29u,7.78,7.46,0.32

**Converting the text in the first_name and last_name columns to title case.**

In [ ]:
treatments_data['first_name']=treatments_data['first_name'].str.title()
treatments_data['last_name']=treatments_data['last_name'].str.title()

In [ ]:
#Removing Special char in name

treatments_data['first_name'] = treatments_data['first_name'].apply(remove_special_chars)

treatments_data['last_name'] = treatments_data['last_name'].apply(remove_special_chars)

In [ ]:
treatments_data

,first_name,last_name,auralin,novodra,hba1c_start,hba1c_end,hba1c_change
0,Veronika,Jindrov,41u - 48u,-,7.63,7.20,0.43
1,Elliot,Richardson,-,40u - 45u,7.56,7.09,0.47
2,Yukitaka,Takenaka,-,39u - 36u,7.68,7.25,0.43
3,Skye,Gormanston,33u - 36u,-,7.97,7.62,0.35
4,Alissa,Montez,-,33u - 29u,7.78,7.46,0.32
...,...,...,...,...,...,...,...
65,Rovzan,Kishiev,32u - 37u,-,7.75,7.41,0.34
66,Jakob,Jakobsen,-,28u - 26u,7.96,7.51,0.45
67,Bernd,Schneider,48u - 56u,-,7.74,7.44,0.30
68,Berta,Napolitani,-,42u - 44u,7.68,7.21,0.47
69,Armina,Sauv,36u - 46u,-,7.86,7.40,0.46

In [ ]:
treatments_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 350 entries, 0 to 69
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   first_name    350 non-null    object
 1   last_name     350 non-null    object
 2   auralin       350 non-null    object
 3   novodra       350 non-null    object
 4   hba1c_start   350 non-null    float64
 5   hba1c_end     350 non-null    float64
 6   hba1c_change  350 non-null    float64
dtypes: float64(3), object(4)
memory usage: 21.9+ KB

**Assign values to new columns ('medicine_name' and 'trial_dosage')**

In [ ]:
treatments_data['medicine_name'] = treatments_data.apply(
    lambda row: 'novodra' if row['auralin'] == '-' else 'auralin', axis=1
)

In [ ]:
treatments_data['trial_dosage'] = treatments_data.apply(
    lambda row: row['novodra'] if row['auralin'] == '-' else row['auralin'], axis=1
)

In [ ]:
treatments_data = treatments_data.drop(['auralin', 'novodra'], axis=1)

**Drop unnecessary columns ('auralin' and 'novodra') after assigning their values to new columns**

In [ ]:
treatments_data

,first_name,last_name,hba1c_start,hba1c_end,hba1c_change,medicine_name,trial_dosage
0,Veronika,Jindrov,7.63,7.20,0.43,auralin,41u - 48u
1,Elliot,Richardson,7.56,7.09,0.47,novodra,40u - 45u
2,Yukitaka,Takenaka,7.68,7.25,0.43,novodra,39u - 36u
3,Skye,Gormanston,7.97,7.62,0.35,auralin,33u - 36u
4,Alissa,Montez,7.78,7.46,0.32,novodra,33u - 29u
...,...,...,...,...,...,...,...
65,Rovzan,Kishiev,7.75,7.41,0.34,auralin,32u - 37u
66,Jakob,Jakobsen,7.96,7.51,0.45,novodra,28u - 26u
67,Bernd,Schneider,7.74,7.44,0.30,auralin,48u - 56u
68,Berta,Napolitani,7.68,7.21,0.47,novodra,42u - 44u
69,Armina,Sauv,7.86,7.40,0.46,auralin,36u - 46u

In [ ]:
treatments_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 350 entries, 0 to 69
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   first_name     350 non-null    object
 1   last_name      350 non-null    object
 2   hba1c_start    350 non-null    float64
 3   hba1c_end      350 non-null    float64
 4   hba1c_change   350 non-null    float64
 5   medicine_name  350 non-null    object
 6   trial_dosage   350 non-null    object
dtypes: float64(3), object(4)
memory usage: 21.9+ KB

**Cleaning data in treatments table**
*  Created a new column hba1c_change which is the difference between hba1c_start and hba1c_end.
*   Concatenated the treatments and treatments_cut dataframes.
*   Renamed the columns given_name and surname to first_name and last_name.
*  Converted the text in the first_name and last_name columns to title case.



*   Assign values to new columns ('medicine_name' and 'trial_dosage') based on conditions in existing columns ('auralin' and 'novodra') using lambda functions.

* Drop unnecessary columns ('auralin' and 'novodra') after assigning their values to new columns.



**Data cleaning  Completed
Cleaning, Transforming, and Merging DataFrames for Analysis and Insight**

In [ ]:
# Convert to CSV
treatments_data.to_csv('treatments_data.csv', index=False)
patients.to_csv('patients_data.csv', index=False)
reactions.to_csv('reaction.csv', index=False)

In [ ]:
#optional or ignore

# Load CSV files
treatments_data = pd.read_csv('treatments_data.csv')
patients_data = pd.read_csv('patients_data.csv')
reaction = pd.read_csv('reaction.csv')

# Merge DataFrames (assuming common column 'patient_id')
final_treatment_data = pd.merge(treatments_data, patients_data, on='first_name')
med_reac = pd.merge(final_treatment_data, reaction, on='first_name')

# Save merged data to CSV
final_treatment_data.to_csv('final_treatment_data.csv', index=False)
med_reac.to_csv('med_reac.csv', index=False)